tasks:
  - name: Build and Load the Extension
    init: chmod 0755 ./extension/build.sh && cd extension && ./build.sh
    command: gp await-port 23000 && code --install-extension ../opensearch-vscode-extension-1.0.0.vsix

  - name: Pre-Commit Hooks Setup
    init: |
      pip install pre-commit &&
      pre-commit install

  - name: Compose Setup
    init: cd demo && docker-compose --env-file env pull
    command: cd demo && docker-compose --env-file env up
  
  - name: Readyness Check
    init: ./demo/check-dashboards.sh
    command: "touch ready.txt"

ports:
  - port: 5601
    onOpen: ignore
  - port: 9200
    onOpen: ignore
  - port: 9600
    onOpen: ignore